#path_data_ingestion_artifact:

data_ingestion:
    location : artifacts/data_ingestion/data.zip
    url: https://www.kaggle.com/api/v1/datasets/download/taweilo/loan-approval-classification-data
    unzip_loc: artifacts/data_ingestion/data

data_transformation:
    data_path : artifacts\data_ingestion\data\loan_data.csv
    to_del : cb_person_cred_hist_length
    to_modify_exp : person_emp_exp
    to_modify_age : person_age
    threshold_value_age : 80
    threshold_value_exp : 30
    transformed_file_path : artifacts\data_transformation\data\transformed_data.csv

feature_engineering:
    data_path : artifacts\data_transformation\data\transformed_data.csv
    train_filepath : artifacts\feature_engineering\data\train.csv
    test_filepath : artifacts\feature_engineering\data\test.csv
    LE_yaml_path : artifacts\feature_engineering\data\le_yaml.yaml