#path_data_ingestion_artifact:

data_ingestion:
    location : artifacts/data_ingestion/data.zip
    url: https://www.kaggle.com/api/v1/datasets/download/vedaantsingh/loan-application-risk-prediction-data