artifact_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://www.kaggle.com/api/v1/datasets/download/vedaantsingh/loan-application-risk-prediction-data
  local_data_file: 